// <auto-generated />
using System;
using Lab1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lab1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260919092805_SeedAlgorithms")]
    partial class SeedAlgorithms
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lab1.Core.Entities.Algorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BigONotation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Algorithms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BigONotation = "O(n^2)",
                            Description = "Простая сортировка обменом",
                            Name = "Сортировка пузырьком"
                        },
                        new
                        {
                            Id = 2,
                            BigONotation = "O(n log n)",
                            Description = "Сортировка Хоара (QuickSort)",
                            Name = "Быстрая сортировка"
                        },
                        new
                        {
                            Id = 3,
                            BigONotation = "O(1)",
                            Description = "",
                            Name = "Константная функция"
                        },
                        new
                        {
                            Id = 4,
                            BigONotation = "O(n)",
                            Description = "",
                            Name = "Сумма элементов"
                        },
                        new
                        {
                            Id = 5,
                            BigONotation = "O(n)",
                            Description = "",
                            Name = "Произведение элементов"
                        },
                        new
                        {
                            Id = 6,
                            BigONotation = "O(n^2)",
                            Description = "",
                            Name = "Полином (в лоб)"
                        },
                        new
                        {
                            Id = 7,
                            BigONotation = "O(n)",
                            Description = "",
                            Name = "Полином (Горнер)"
                        },
                        new
                        {
                            Id = 8,
                            BigONotation = "O(n log n)",
                            Description = "",
                            Name = "Встроенная сортировка (Array.Sort)"
                        },
                        new
                        {
                            Id = 9,
                            BigONotation = "O(n^3)",
                            Description = "",
                            Name = "Умножение матриц"
                        },
                        new
                        {
                            Id = 10,
                            BigONotation = "O(n)",
                            Description = "",
                            Name = "Степень (Наивный)"
                        },
                        new
                        {
                            Id = 11,
                            BigONotation = "O(n)",
                            Description = "",
                            Name = "Степень (Рекурсивный)"
                        },
                        new
                        {
                            Id = 12,
                            BigONotation = "O(log n)",
                            Description = "",
                            Name = "Степень (Быстрый/Бинарный)"
                        });
                });

            modelBuilder.Entity("Lab1.Core.Entities.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmId")
                        .HasColumnType("integer");

                    b.Property<double>("ElapsedMs")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("ExperimentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("N")
                        .HasColumnType("integer");

                    b.Property<int>("RunNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<long>("Steps")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId");

                    b.HasIndex("SessionId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("Lab1.Core.Entities.ExperimentSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlgorithmId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NMax")
                        .HasColumnType("integer");

                    b.Property<int>("RunsPerPoint")
                        .HasColumnType("integer");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId");

                    b.ToTable("ExperimentSessions");
                });

            modelBuilder.Entity("Lab1.Core.Entities.Experiment", b =>
                {
                    b.HasOne("Lab1.Core.Entities.Algorithm", "Algorithm")
                        .WithMany()
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab1.Core.Entities.ExperimentSession", "Session")
                        .WithMany("Experiments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Algorithm");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Lab1.Core.Entities.ExperimentSession", b =>
                {
                    b.HasOne("Lab1.Core.Entities.Algorithm", "Algorithm")
                        .WithMany("Sessions")
                        .HasForeignKey("AlgorithmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Algorithm");
                });

            modelBuilder.Entity("Lab1.Core.Entities.Algorithm", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Lab1.Core.Entities.ExperimentSession", b =>
                {
                    b.Navigation("Experiments");
                });
#pragma warning restore 612, 618
        }
    }
}
